const mongoose =require('mongoose')
const Products =require('./models/productModels')

const main = ()=>{
  mongoose.connect('mongodb://localhost:27017/eCommerce')//mongodb://ip/port/dbname
  .then(console.log('mongoose baglanti okey'))
  .catch((err)=>console.log(err))
}
main()


      

Products.insertMany(
  [

    {
      title: 'The &quot;',
      description: 'Ball is life for your family' ,
      quantity: 09,
      num_favorers: 39,
      tags: [
        'girlfriend gift',
        'dad hat',
        'hats',
        'embroidery',
        'embroidered',
        'baseball cap',
        'personalized gift',
        'Baskteball Mom',
        'Team Mom',
        'Basketball dad hats',
        'Momslife',
        'Mom Coach',
        'Mom Gifts'
      ],
      processing_min: 3,
      processing_max: 5,
      price: 22.99,
      img: 'https://i.etsystatic.com/14221782/r/il/623996/2906244845/il_fullxfull.2906244845_lhor.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'River Bend  2&quot;x4&quot;.',
      description: '',
      quantity: 89,
      num_favorers: 74,
      tags: [
        'Belt Buckle',
        'Birthday',
        'Montana',
        'Barbed Wire',
        'Buckle',
        'Custom Welded',
        'Steel metal',
        'Contemporary Country',
        'Groomsman gifts',
        'Mens or Womens Gift',
        'Father Gift',
        'Boyfriend present',
        'Mens Belt Buckle'
      ],
      processing_min: 5,
      processing_max: 10,
      price: 119.95,
      img: 'https://i.etsystatic.com/7409307/r/il/96f4d3/664611099/il_fullxfull.664611099_n4fv.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Pink and Blue Sequin Face Mask. 2 Tone Sequin Mask. Adults, Washable, Glam Mask, Sequin Mask',
      description: 'Sequin Face Mask',
      quantity: 3,
      num_favorers: 3,
      tags: [
        'Bling Mask',
        'Colorful Mask',
        'Two Tone Mask',
        'Blue Sequin Mask',
        'Pink Sequin Mask',
        'Luxury Mask',
        'Sequin Mask',
        'Washable Mask',
        'Fashion Mask',
        'Face Mask'
      ],
      processing_min: 3,
      processing_max: 5,
      price: 21,
      img: 'https://i.etsystatic.com/25629522/r/il/0ea872/2678876474/il_fullxfull.2678876474_bn96.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Blue White Peach Pink Patterned Face Mask Chain / Face Mask  Necklace / Gift for her / Face Mask Chain Holder Lanyard',
      description: 'Handmade Face Mask Chain. Fully Customizable! Pick your colors, add your name, support your favorite sports team, rock your school colors or even make it fancy with crystals! So many possibilities. Great for Adults and Kids!',
      quantity: 4,
      num_favorers: 17,
      tags: [
        'face mask chain',
        'face mask necklace',
        'face mask lanyard',
        'cyber monday',
        'mask holder',
        'face mask',
        'beaded necklace',
        'gift for her',
        'mask necklace',
        'face mask kids',
        'face mask adults',
        'eye glass chain',
        'back to work'
      ],
      processing_min: 3,
      processing_max: 5,
      price: 12,
      img: 'https://i.etsystatic.com/24468208/r/il/9731e0/2616324193/il_fullxfull.2616324193_c82g.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: '37&quot;-40&quot; Maasai beaded belt, Leather beaded belt, Unisex leather belt',
      description: 'MEASUREMENT IS TAKEN FROM WHERE THE BUCKLE JOINS THE LEATHER TO THE FIRST & TO THE LAST OF 5 HOLES',
      quantity: 1,
      num_favorers: 10,
      tags: [
        'Unique belt',
        'Ladies belt',
        'Masai beaded belt',
        'Men gifts',
        'Belt',
        'Leather belts',
        'Leather belt',
        'Accessories',
        "children's belt"
      ],
      processing_min: 1,
      processing_max: 3,
      price: 58,
      img: 'https://i.etsystatic.com/16294850/r/il/2fca03/3398669710/il_fullxfull.3398669710_kksu.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Travel bandage for baby',
      description: 'Travel bandage, essential to complete the baby exchange bag. Soft cotton fabric with padding and interior in printed waterproof fabric, very easy to clean. The interior in waterproof fabric does not have a &quot;plastic&quot; effect but has a fabric-type workmanship that makes it very soft and comfortable. Very comfortable even for the sea bag to take to the beach. Measurements are: open 70 x 49 cm, closed 24 x 20 cm',
      quantity: 1,
      num_favorers: 0,
      tags: [
        'travel changing table',
        'diaper change',
        'baby bandage',
        'baby accessories',
        'accessories newborn',
        'birth gift idea',
        'gearbox mattress',
        'new born',
        'baby exchange bag',
        'Bath'
      ],
      processing_min: 1,
      processing_max: 2,
      price: 32,
      img: 'https://i.etsystatic.com/17343440/r/il/f1e563/2193297777/il_fullxfull.2193297777_afi5.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Elf hairbow, Christmas hairbow,  Toddler hairbow,  Small hairbow, 3 inch faux leather Christmas elf bow',
      description: 'This listing is for one faux leather 3 inch hairbow.  This bow measures just over 3 inches and is attached to an alligator clip with a non slip grip.',
      quantity: 2,
      num_favorers: 2,
      tags: [
        'girls hairbow',
        'toddler hair clips',
        'toddler hairbow',
        'christmas hairbow',
        'red and white bow',
        'small hairbows',
        'red hairbow',
        'Christmas hair clip',
        'elf hair clip',
        'elf hairbow',
        'Christmas elf',
        'white and red bow',
        '3 inch hairbow'
      ],
      processing_min: 1,
      processing_max: 2,
      price: 3.99,
      img: 'https://i.etsystatic.com/19376249/r/il/fe9d3c/2676581082/il_fullxfull.2676581082_lib2.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'ROBERTO CAVALLI. +NEW+ Rimless Eyewear Gold Plated. Rimatara 701 028. Made in Italy',
      description: 'Brand:\tROBERTO CAVALLI',
      quantity: 1,
      num_favorers: 3,
      tags: [
        'ROBERTO CAVALLI',
        'NEW',
        'Rimless Eyewea',
        'Gold Plated',
        'Rimatara 701 028',
        'Made in Italy'
      ],
      processing_min: 3,
      processing_max: 5,
      price: 450,
      img: 'https://i.etsystatic.com/23025860/r/il/f590c5/3011438492/il_fullxfull.3011438492_3piw.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Cotton shawl',
      description: 'Cotton thread shawl, diamond shaped and tassels at all four ends.',
      quantity: 1,
      num_favorers: 9,
      tags: [ 'Crochet', 'Wool', 'Cotton', 'Shawl', 'Work' ],
      processing_min: 1,
      processing_max: 1,
      price: 35.2,
      img: 'https://i.etsystatic.com/10308572/r/il/842e62/1652871607/il_fullxfull.1652871607_njfz.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Newsboy Cap, Boys Flat Cap, Kids Grey Corduroy Newsboy Cap - Children',
      description: 'This GREY Corduroy newsboy cap has long been a favorite in Tweed and Linen. ‘What about corduroy?’ a customer asked. We listened, and very good it is too!',
      quantity: 5,
      num_favorers: 0,
      tags: [
        'grey boys cap',
        'grey children cap',
        'grey newsboy cap',
        'grey Scally cap kids',
        'grey baby cap',
        'grey newsboy',
        'grey kids flat cap',
        'grey ivy cap kids'
      ],
      processing_min: 1,
      processing_max: 1,
      price: 18,
      img: 'https://i.etsystatic.com/8557689/r/il/9818be/3423987381/il_fullxfull.3423987381_kqzt.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Boerboel South African Mastiff Breed of Dog Lanyard Key Card Holder Perfect Gift',
      description: 'The complete length that goes around your neck measures approximately 91.5cm or 36 inches and just less than 2.5cm or 1 inch wide not including the metal fittings.',
      quantity: 3,
      num_favorers: 5,
      tags: [
        'Dog',
        'Pet',
        'Dog theme gift',
        'Pet themed gift',
        'lanyard',
        'key holder',
        'keyring',
        'card holder',
        'work lanyard',
        'dog lanyard',
        'Boerboel',
        'Boerboel lanyard',
        'mastiff lanyard'
      ],
      processing_min: 1,
      processing_max: 2,
      price: 9.99,
      img: 'https://i.etsystatic.com/12030156/r/il/d65245/2109668405/il_fullxfull.2109668405_fegi.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Christmas face Mask - festive face covering - Small, Medium, Large - novelty gift',
      description: 'Why not make your face mask festive with these Christmas themed coverings!',
      quantity: 14,
      num_favorers: 0,
      tags: [
        'Christmas theme',
        'Facial coverings',
        'gifts for him',
        'gifts for her',
        'the grinch',
        'bah humbug',
        'covid19 masks',
        'christmas face mask',
        'ya filthy animal',
        'novelty gift ideas',
        'corona virus',
        'xmas stocking filler',
        'Christmas 2021'
      ],
      processing_min: 5,
      processing_max: 10,
      price: 9,
      img: 'https://i.etsystatic.com/13773914/r/il/745624/2531589926/il_fullxfull.2531589926_f6nf.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Cotton Bow ties for man handmade with Grid Pattern Suit Groomsmen Pocket Square set Party and Wedding Bowties Stripe Pattern in Gold',
      description: 'One of the best groomsman accessories, the necktie, bowties, and pocket square are suitable for different circumstances like a party, wedding, opening day, back to school or even on a date! ',
      quantity: 999,
      num_favorers: 1,
      tags: [
        'groomsmen',
        'bow ties',
        'bowtie for man',
        'bowtie for boy',
        'adjustable bow tie',
        'handmade',
        'party dress code',
        'wedding',
        'Wedding gress',
        'Bird print',
        'Necktie',
        'Pocket square',
        'back to school'
      ],
      processing_min: 3,
      processing_max: 5,
      price: 90,
      img: 'https://i.etsystatic.com/22254155/r/il/50acfd/2461586358/il_fullxfull.2461586358_kph3.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Cashmere Fingerless Gloves - Upcycled Cashmere Handwarmers - Made from a Recycled Cashmere Sweater - blue cashmere with crocheted edging - M',
      description: 'These cozy fingerless gloves are made from an upcycled sweater. The blue cashmere is soft and warm, using the edge from the sweater as the cuff. The hand edge is crocheted with a pretty blue yarn, making a comfortable, flexible fit. ',
      quantity: 1,
      num_favorers: 0,
      tags: [
        'handwarmers',
        'fingerless gloves',
        'fingerless',
        'upcycled cashmere',
        'upcycled wool',
        'wristlets',
        'armwarmers',
        'upcycled handwarmers',
        'upcycled gloves',
        'upcycled fingerless',
        'cashmere gloves',
        'cashmere handwarmers',
        'cashmere fingerless'
      ],
      processing_min: 1,
      processing_max: 3,
      price: 28,
      img: 'https://i.etsystatic.com/11078930/r/il/e455a0/3532186534/il_fullxfull.3532186534_9p3m.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Baby Headband/New Baby Gift/ Hairbow/Baby Shower Gift/1st Birthday Gift/Baby Girl/Hair Bow/Baby Gift Set/Ribbed Hairband/Girls Hair Bow',
      description: 'Beautiful Ribbed Headbands',
      quantity: 668,
      num_favorers: 18,
      tags: [
        'New baby',
        'baby gift',
        'baby girl gift',
        'baby hairbow',
        'baby hair accessory',
        'baby accessories'
      ],
      processing_min: 1,
      processing_max: 1,
      price: 3.99,
      img: 'https://i.etsystatic.com/24737566/r/il/917fea/3638604056/il_fullxfull.3638604056_3olk.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Girl and baby hair band in cotton jersey, headbands, turban',
      description: 'Our creations are the result of the imagination of our designer Valentina who creates each item by hand.',
      quantity: 1,
      num_favorers: 0,
      tags: [
        'sash',      'elastic',
        'heandband', 'turban',
        'tiara',     'Baby',
        'girl',      'Girls'
      ],
      processing_min: 1,
      processing_max: 3,
      price: 12,
      img: 'https://i.etsystatic.com/17460843/r/il/0605f3/3059150231/il_fullxfull.3059150231_iswg.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'READY TO SHIP / Knit Mohair Turban, Winter Headband, Soft Kid Mohair, Women Knitted Headband, Knit Ear Warmer, Mohair Luxury Wool',
      description: 'Hand knit turban headband in kid mohair blend that feels super soft and cozy on the skin. With a snugly fit that ensures protection from the cold and a draped design that allows you to adjust its width',
      quantity: 7,
      num_favorers: 3,
      tags: [
        'Knit Mohair Turban',
        'Winter Headband',
        'Knit Ear Warmer',
        'Super Soft Headband',
        'Women Headbands',
        'Knitted Headband',
        'Warm Mohair Wool',
        'premium quality knit',
        'snugly head warmer',
        'plexida luxury gift',
        'dark grey headband',
        'soft Kid Mohair',
        'bridesmaid gift'
      ],
      processing_min: 1,
      processing_max: 3,
      price: 38,
      img: 'https://i.etsystatic.com/7558906/r/il/aa400d/1720554240/il_fullxfull.1720554240_ftis.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Girl and baby hair band in cotton jersey, headbands, turban',
      description: 'Our creations are the result of the imagination of our designer Valentina who creates each item by hand.',
      quantity: 1,
      num_favorers: 0,
      tags: [ 'Bands', 'turban', 'tiara', 'girl', 'fixings', 'elastic' ],
      processing_min: 1,
      processing_max: 3,
      price: 13,
      img: 'https://i.etsystatic.com/17460843/r/il/cec8b6/3011440772/il_fullxfull.3011440772_t43x.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'READY TO SHIP / Mens Beanie Hat, Slouchy Winter Hat, Boyfriend Beanie, Rolled up Beanie, Customizable Beanie, Made to Order',
      description: 'Hand knit beanie hat, made from a warm and soft wool blend. You can adjust the hat to your prefer fitting; roll up the rib for a snug fit or leave it unrolled for a slouchy one (or roll some of it for something in between!). Ready to ship in selected colors and  in two sizes, women&#39;s and men&#39;s',
      quantity: 29,
      num_favorers: 4,
      tags: [
        'Turn Up Beanie',
        'Mens Beanie Hat',
        'Slouchy Beanie',
        'Boyfriend Beanie',
        'Rolled up Beanie',
        'Snug Beanie',
        'Customizable Beanie',
        'Light Grey Beanie',
        'Slouchy Winter Hat',
        'Wool Skit Hat',
        'Unisex Woolen Hat',
        'Tight Womens Beanie',
        'gifts for him'
      ],
      processing_min: 1,
      processing_max: 3,
      price: 38,
      img: 'https://i.etsystatic.com/7558906/r/il/53eccd/2083796290/il_fullxfull.2083796290_3izh.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Metal keychain with desired engraving Model: Truck with desired engraving',
      description: 'Metal keychain with your personal engraving',
      quantity: 100,
      num_favorers: 0,
      tags: [
        'Favorite person',
        'Gift for men',
        'Gift for women',
        'Text',
        'Keychain with engraving',
        'Key fob',
        'Favorite Person Pendant',
        'Pendant with engraving',
        'Trailer personalized',
        'Gift',
        'Partner Keychain',
        'Love',
        'Keychain Engraving'
      ],
      processing_min: 1,
      processing_max: 2,
      price: 16.9,
      img: 'https://i.etsystatic.com/15676571/r/il/89b019/3537767828/il_fullxfull.3537767828_srqu.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Teapot Keychain VERY SMALL Tea Pot Keyring Tea Keychain Tea Gift Tea Cup Keychain Mother&#39;s Day Keychain Tea Party Gift Bridesmaid Keychain',
      description: 'This listing is for a personalized gold teapot and teacup keychain with a hand-stamped initial charm. This can be made into a necklace instead, just choose your chain-length from the drop-down menu. You will be able to choose between a key ring, link chain, or ball chain when checking out. You will also be able to choose your initial! :) **Please see the second picture for scale. This is a VERY SMALL charm.',
      quantity: 1,
      num_favorers: 34,
      tags: [
        'keychain',
        'custom keychain',
        'metalspeaktoo',
        'mothers day keychain',
        "mother's day gift",
        'bridesmaid keychain',
        'teacup keychain',
        'teapot keychain',
        'tea pot keyring',
        'tea keychain',
        'tea gift',
        'tea party gift',
        'personalized'
      ],
      processing_min: 3,
      processing_max: 5,
      price: 18.95,
      img: 'https://i.etsystatic.com/10075634/r/il/3bc0bb/753819794/il_fullxfull.753819794_no7k.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Nuno Felt Scarf',
      description: 'This beautiful pink and brown scarf is made using soft merino wool and tussah silk fibers. It is a perfect addition to your wardrobe.',
      quantity: 1,
      num_favorers: 9,
      tags: [],
      processing_min: 1,
      processing_max: 3,
      price: 65,
      img: 'https://i.etsystatic.com/10938221/r/il/bfa8cc/2729701700/il_fullxfull.2729701700_9o42.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Necktie Crochet',
      description: 'For that special someone that craves to &quot;not be like everyone else&quot;',
      quantity: 1,
      num_favorers: 0,
      tags: [
        'necktie',
        'crochet tie',
        'one of a kind',
        'one of a kind gift',
        'special gift',
        'Gift'
      ],
      processing_min: 1,
      processing_max: 2,
      price: 20,
      img: 'https://i.etsystatic.com/32633468/r/il/daed19/3537765828/il_fullxfull.3537765828_tmrg.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Vintage Sunglasses Daytona DA 857S Safilo authentic Aviator glasses wiht original sun lenses Made in Italy New Old Stock',
      description: 'DAYTONA VINTAGE SUNGLASSES',
      quantity: 1,
      num_favorers: 2,
      tags: [
        'Vintage eyewear',
        'Vintage',
        'Made in Italy',
        'Handmade',
        'Safilo',
        'Lunettes',
        'Vintage sunglasses',
        'Persol',
        'Aviator',
        'Tortoise',
        'Daytona',
        'designer sunglasses',
        'Steampunk'
      ],
      processing_min: 1,
      processing_max: 2,
      price: 93,
      img: 'https://i.etsystatic.com/17851528/r/il/70ea7c/2305347751/il_fullxfull.2305347751_5165.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Custom Warrant Officer Leather Patch Beanie | Eagle Rising',
      description: 'Super warm and cozy beanie with custom engraved leather patch.',
      quantity: 8,
      num_favorers: 10,
      tags: [
        'warrant officer gear',
        'new warrant officer',
        'WO class swag',
        'Eagle rising',
        'warrant officer swag',
        'army warrant officer',
        'retirement gift',
        'warrant officer',
        'mens beanie',
        'leather patch',
        'leather beanie',
        'engraved leather hat',
        'leather engraved'
      ],
      processing_min: 3,
      processing_max: 5,
      price: 20,
      img: 'https://i.etsystatic.com/23003262/r/il/c700dd/3611058611/il_fullxfull.3611058611_d8zf.jpg',
      onSale: true,
      taxonomy_id: 1
    },
    {
      title: 'Go Your Own Way Vintage Style Lyrics Typography wall art print framed',
      description: 'Statement Lyrics typography art print. Go Your Own Way vintage style typography.',
      quantity: 2698,
      num_favorers: 8,
      tags: [],
      processing_min: 1,
      processing_max: 2,
      price: 9.99,
      img: 'https://i.etsystatic.com/20219766/r/il/56b6cd/3759507769/il_fullxfull.3759507769_95ei.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'Surfing Svg, Surfer Man Riding Wave Silhouette, Palm Tree, Beach Life, Sublimation Design, SVG Scalable Vector Graphics',
      description: 'Surfing Silhouette Design drawn by me.',
      quantity: 200,
      num_favorers: 0,
      tags: [
        'surf',
        'svg',
        'surfing',
        'summer beach',
        'palm tree beach',
        'surfboard svg',
        'summer vibes',
        'ocean wave svg',
        'beach summer svg',
        'palm tree',
        'summer time',
        'ocean wave',
        'riding wave'
      ],
      processing_min: null,
      processing_max: null,
      price: 3.3,
      img: 'https://i.etsystatic.com/25467458/r/il/47d1b7/3860616075/il_fullxfull.3860616075_1x2q.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'file SVG mom to be kinder surprise, compatible with plotter cricut silhouette scanncut',
      description: 'Svg files to create maternity party t-shirts and gadgets, gender reveal and new arrival announcement.',
      quantity: 89,
      num_favorers: 17,
      tags: [
        'mom to be',
        'premaman',
        'svg',
        'cricut',
        'silhouette',
        'svg kinder',
        'kinder surprise',
        'gender reveal'
      ],
      processing_min: null,
      processing_max: null,
      price: 1,
      img: 'https://i.etsystatic.com/18444289/r/il/c76f7b/2967992154/il_fullxfull.2967992154_9tww.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'ARCTIC WOLF ARTWORKS for Living Room, Forest Double Exposure Prints, Animal Canvas Art, Above Bed Decor, Oversized Wall Art',
      description: '',
      quantity: 10989,
      num_favorers: 0,
      tags: [
        '3 CANVAS WALL ART',
        'ABOVE BED DECOR',
        'ANIMAL PORTRAIT',
        'ARCTIC WOLF ARTWORKS',
        'BEST FRIEND GIFT',
        'FRAMED CANVAS',
        'HOME OFFICE GIFTS',
        'LIVING ROOM PRINTS',
        'MODERN PRINTS',
        'NATURE LANDSCAPE',
        'OVERSIZED WALL ART',
        'TREE DOUBLE EXPOSURE',
        'WILDLIFE CANVAS'
      ],
      processing_min: 1,
      processing_max: 3,
      price: 34.74,
      img: 'https://i.etsystatic.com/34503997/r/il/aba729/3813094526/il_fullxfull.3813094526_2myf.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'Terry price difference',
      description: 'This is an addition to the main order.Do not buy alone. 🎨',
      quantity: 949,
      num_favorers: 0,
      tags: [
        'add deceased',
        'digital portrait',
        'add loved one',
        'drawing from photo',
        'personalized gift',
        'loss of loved one',
        'memorial portrait',
        'combine merge photos',
        'add family member',
        'black and white',
        'photo editing',
        'custom drawing',
        'sepia photo gift'
      ],
      processing_min: null,
      processing_max: null,
      price: 4.35,
      img: 'https://i.etsystatic.com/32543643/r/il/02e429/3812221004/il_fullxfull.3812221004_60f7.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'She is Strong License Plate PNG Sublimation Design, She is Strong Png,License Plate Png, Car License Plate Templates, Digital Downloads',
      description: 'This listing is for the\.',
      quantity: 964,
      num_favorers: 52,
      tags: [
        'instant download',
        'sublimation design',
        'license plate png',
        'license templates',
        'car license plate'
      ],
      processing_min: null,
      processing_max: null,
      price: 4,
      img: 'https://i.etsystatic.com/28158696/r/il/5a9a73/3655640478/il_fullxfull.3655640478_50u3.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'Custom character commission for RPG',
      description: 'Custom character commission ',
      quantity: 10,
      num_favorers: 845,
      tags: [
        'commission art',
        'character',
        'concept art',
        'rpg',
        'illustration'
      ],
      processing_min: 5,
      processing_max: 10,
      price: 60,
      img: 'https://i.etsystatic.com/21889911/r/il/01d816/2754990283/il_fullxfull.2754990283_4gqz.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'Choose Your Album Poster | Custom Album Cover Print, Music Poster, Wall Art, Music Gift',
      description: 'Custom Album Poster - designed by RB Prints.',
      quantity: 17,
      num_favorers: 95,
      tags: [
        'Art',
        'poster',
        'print',
        'wall decor',
        'Album cover',
        'Music Poster',
        'Music Print',
        'Music art',
        'Custom Album cover',
        'Choose your own',
        'Custom music print',
        'Custom album',
        'Personalised Poster'
      ],
      processing_min: 1,
      processing_max: 3,
      price: 5.99,
      img: 'https://i.etsystatic.com/27978583/r/il/dc1e6b/3570527792/il_fullxfull.3570527792_3ay0.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'raise them wild svg floral svg raise them kind svg wild and free svg wildflowers raising wildflowers svg trendy shirt design retro boho svg',
      description: 'raise them wild svg floral svg raise them kind svg wild and free svg wildflowers raising wildflowers svg trendy shirt design retro boho svg',
      quantity: 12,
      num_favorers: 13,
      tags: [
        'raise them wild',
        'raise them kind',
        'wild and free svg',
        'wildflowers',
        'raising wildflowers',
        'raising wild things',
        'wild things',
        'svg',
        'trendy shirt design',
        'wildflowers svg',
        'boho svg',
        'retro svg',
        'cricut svg'
      ],
      processing_min: null,
      processing_max: null,
      price: 4.29,
      img: 'https://i.etsystatic.com/27223766/r/il/45d45d/3582532387/il_fullxfull.3582532387_t9jj.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'PRINTABLE Happy Birthday Card | Gender Neutral Baby Card | Birthday Card for Kids | Instant Download Card | Minimal Birthday Card',
      description: 'This is a listing for a super cute and minimalistic printable birthday card. Simply download, print, cut it out and fold down the middle to create this greeting card ready to use. ',
      quantity: 99,
      num_favorers: 0,
      tags: [
        'A6 Card',
        'Genderneutral',
        'Birthday for Kids',
        'Toddler Gift',
        'Celebration',
        'first birthday',
        'minimalistic',
        'animal',
        'cute gift',
        'toddler',
        'baby gift',
        'babyshower',
        'smiley'
      ],
      processing_min: null,
      processing_max: null,
      price: 4,
      img: 'https://i.etsystatic.com/34000925/r/il/13a9e1/3813090560/il_fullxfull.3813090560_osbl.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'Valentinstag-Liebes-Illustrations-Satz,Paar Clipartt, Hochzeit Clipart, Liebe Paar ClipArt, Paar Portrait PNG.',
      description: '',
      quantity: 999,
      num_favorers: 0,
      tags: [
        'Cute couple sitting clipart',
        'Male and Female',
        'Valentine Day clipart',
        'Valentine Day',
        'Pair of clipart',
        'Dear Couple ClipArt',
        'Pair Portrait PNG',
        'Couple Clipart',
        'Male Clipart',
        'Boyfriend Girlfriend Clipart',
        'Female Clipart',
        'Love clipart',
        'couple sitting clipart'
      ],
      processing_min: null,
      processing_max: null,
      price: 6.99,
      img: 'https://i.etsystatic.com/34740155/r/il/70af19/3860602583/il_fullxfull.3860602583_nc4h.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'Muhammad Ali Poster, Black And White, Muhammad Ali Print, Muhammad Ali Canvas, Muhammad Ali Wall Art, Boxing Poster, Vintage Poster',
      description: 'Muhammad Ali Poster, Black And White, Muhammad Ali Print, Muhammad Ali Canvas, Muhammad Ali Wall Art, Boxing Poster, Vintage Poster',
      quantity: 58,
      num_favorers: 135,
      tags: [
        'Muhammad Ali Poster',
        'Black And White',
        'Muhammad Ali Print',
        'Muhammad Ali Canvas',
        'Boxing Poster',
        'Vintage Poster',
        'Muhammad Ali',
        'Wall Art',
        'Poster Print',
        'Gym Poster',
        'Muhammad Ali Art',
        'Canvas Art',
        'Canvas Print'
      ],
      processing_min: null,
      processing_max: null,
      price: 10,
      img: 'https://i.etsystatic.com/25510945/r/il/a7708b/3395866343/il_fullxfull.3395866343_e6ak.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'Fraggle Rock',
      description: 'Please Note:',
      quantity: 91,
      num_favorers: 18,
      tags: [
        'Fraggle Rock', 'Muppet',
        'Jim Henson',   '80s',
        'TV',           'Gobo',
        'Red',          'Mokey',
        'Wembley',      'Boober',
        'doozers'
      ],
      processing_min: null,
      processing_max: null,
      price: 1.99,
      img: 'https://i.etsystatic.com/18590127/r/il/49676d/3478483593/il_fullxfull.3478483593_5rud.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'Lets Cruise Ship Ocean Sublimation Print - Ready to Press! Shipped Sublimation',
      description: 'Sizes:',
      quantity: 480,
      num_favorers: 31,
      tags: [
        'sublimation',
        'sublimation prints',
        'sublimation transfer',
        'mailed sublimation',
        'Disney Sublimation',
        'Disney',
        'Disney png',
        'Fall Vibes Disney',
        'Lets Cruise',
        'Cruise Sublimation',
        'Disney Cruise',
        'Retro Cruise',
        'Kids Cruise'
      ],
      processing_min: 2,
      processing_max: 3,
      price: 0.99,
      img: 'https://i.etsystatic.com/10370982/r/il/ae3245/3372120857/il_fullxfull.3372120857_7x53.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'SEXY WOMAN POSTER Prints for Bedroom, Model Girl Decor, Makeup Lady Art, Trendy Room Canvas, 3 Piece Canvas Wall Art',
      description: '',
      quantity: 10989,
      num_favorers: 0,
      tags: [
        '3 CANVAS WALL ART',
        'AFFORDABLE DECOR',
        'BEST FRIEND GIFT',
        'ELEGANT ROOM DECOR',
        'GUEST ROOM INTERIOR',
        'HOME OFFICE POSTER',
        'LUXURY HOME POSTERS',
        'MAKEUP LADY ART',
        'MODEL GIRL DECOR',
        'NUDE WOMAN PRINTS',
        'OVERSIZED WALL ART',
        'SEXY WOMAN POSTER',
        'TRENDY ROOM CANVAS'
      ],
      processing_min: 1,
      processing_max: 3,
      price: 34.74,
      img: 'https://i.etsystatic.com/34503997/r/il/92b8e3/3860616229/il_fullxfull.3860616229_9xhj.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'Bella Canvas 3501 Heather Forest Mockup, Bella 3501 Heather Forest, Heather Forest mockup, Mockup, Bella Mockup, Heather Forest 3501',
      description: 'DESCRIPTION',
      quantity: 40,
      num_favorers: 1,
      tags: [
        'Bella Canvas mockup',
        'Flat Lay mockup',
        'Bella Mockup',
        '3501',
        'Bella 3501',
        'Fall Bella 3501',
        'Bella 3501 Fall',
        '3501 Mockup',
        'Mockup',
        'Long Sleeve Mockup',
        '3501 Forest',
        'Heather Forest',
        '3501 Green Mockup'
      ],
      processing_min: null,
      processing_max: null,
      price: 6,
      img: 'https://i.etsystatic.com/19772879/r/il/c918ae/3279566643/il_fullxfull.3279566643_c6ie.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'Bella Canvas B8882 Mauve Crop mockup, Bella 8882 Mauve, Crop Top mockup, Mauve t-shirt mockup, Flat Lay mockup, Bella Mockup',
      description: 'DESCRIPTION',
      quantity: 40,
      num_favorers: 1,
      tags: [
        'Bella Canvas mockup',
        'Flat Lay mockup',
        'Bella Mockup',
        'B8882 Crop Mockup',
        'Bella Crop Mockup',
        'Bella B8882 Mockup',
        'Bella T-shirt Mockup',
        'B8882 Mauve',
        'B8882 Mauve Mockup',
        'Bella B8882 Mauve',
        'Mauve Crop Top',
        'Bella Mauve B8882',
        'Bella B8882 Flat Lay'
      ],
      processing_min: null,
      processing_max: null,
      price: 6,
      img: 'https://i.etsystatic.com/19772879/r/il/44ed78/3281460745/il_fullxfull.3281460745_ceuq.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'Blue Jays Png Retro Vintage, Baseball font Png, City Png, Baseball Png, Sport Png,Hand Drawn Blue Jays Baseball Shirt Print, Toronto Retro',
      description: 'PNG - DIGITAL DOWNLOAD',
      quantity: 97,
      num_favorers: 0,
      tags: [
        'Png sublimination',
        'svg for sticker',
        'baseball svg',
        'baseball shirt svg',
        'hand drawn svg',
        'phillies svg',
        'phillies cricut',
        'phillies dxf',
        'city svg',
        'baseball cricut',
        'bat svg',
        'sport Png',
        '300dpi'
      ],
      processing_min: null,
      processing_max: null,
      price: 5,
      img: 'https://i.etsystatic.com/29351616/r/il/745b18/3813085586/il_fullxfull.3813085586_489l.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: 'Bella Canvas 3501 Grey Tri-blend Mockup, Grey Tri-blend, t-shirt mockup, Flat Lay mockup, Bella Mockup, Grey unisex, Long sleeve',
      description: 'DESCRIPTION',
      quantity: 40,
      num_favorers: 6,
      tags: [
        'Bella Canvas mockup',
        'Bella Mockup',
        'Grey Tri-blend',
        'Bella 3501 Grey',
        'Bella 3501',
        '3501 Grey Mockup',
        'Long Sleeve Mockup',
        'Nurse T-shirt Mockup',
        '3501 Long Sleeve',
        'Bella Long Sleeve',
        '3501 Grey Tri-Blend',
        'Long Sleeve Gray',
        'Bella 3501 Gray'
      ],
      processing_min: null,
      processing_max: null,
      price: 6,
      img: 'https://i.etsystatic.com/19772879/r/il/133b0c/3271325452/il_fullxfull.3271325452_80qa.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    {
      title: '1988-89 FIVE Celtic &quot;Not The View&quot; Celtic Fanzine Magazines 30 + Pages Each. Ideal Christmas Gift, Fathers Day, Birthday Present For Him',
      description: '1988-89 Original FIVE Celtic &quot;Not The View&quot; Celtic Fanzine Magazines 30 + Pages Each.',
      quantity: 1,
      num_favorers: 2,
      tags: [
        'gift ideas',
        'fathers day',
        'birthday present',
        'christmas gift',
        'Celtic FC',
        'Celtic memorabilia',
        'Celtic collectables',
        'Celtic Football',
        'Celtic Handbook',
        '1988-89 Celtic FC',
        '1988 Celtic FC',
        '1989 Celtic FC',
        'Celtic Fanzine'
      ],
      processing_min: 1,
      processing_max: 1,
      price: 32.99,
      img: 'https://i.etsystatic.com/9105102/r/il/302acd/2728684526/il_fullxfull.2728684526_jspn.jpg',
      onSale: true,
      taxonomy_id: 2
    },
    
  ]


).then(console.log('seeds geleiyor'))
.catch(err=>console.log(err))
 